# Generated by Django 4.0.1 on 2022-01-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_second_image_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
