# Generated by Django 4.0.1 on 2022-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
