# Generated by Django 4.0.1 on 2022-02-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('product', '0007_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.productmaterial'),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.productshape'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.productusage'),
        ),
    ]
