# Generated by Django 4.0.1 on 2022-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('main_image', models.ImageField(upload_to='images/collection')),
                ('secondary_image', models.ImageField(upload_to='images/collection')),
                ('featured_collection', models.BooleanField(default='N')),
            ],
        ),
    ]
