# Generated by Django 4.0.1 on 2022-01-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_collection_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='category_name',
            new_name='collection_name',
        ),
    ]
